language: node_js

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run lint
    - stage: deploy
      if: branch = makoto
      script:
        - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: makoto