language: node_js

script:
  - npm run test
  - npm run lint

before_deploy:
  - src/setVersion.sh $TRAVIS_TAG
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    tags: true