name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun ci

      - run: bun run build

      - name: Restructure build output
        run: |
          mkdir -p deploy/excel-csv-import
          cp -r build/. deploy/excel-csv-import/

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      - uses: actions/deploy-pages@v4
